######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 1 22:41:12 2014
######################################################################

TEMPLATE = app
CONFIG += debug
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += `pkg-config x11 --libs`

# Input
HEADERS += Indicator.hh IndicatorApplication.hh Preferences.hh SplashScreen.hh
SOURCES += keylock-applet.cc Indicator.cc IndicatorApplication.cc Preferences.cc
